language: csharp
mono: none
dotnet: 2.2
dist: xenial
sudo: required
script:
 - dotnet restore
 - dotnet build
 - app/build/compile.sh
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
